### PR TITLE
Add support for Groq!

### PR DESCRIPTION
**Pull request by vanpelt**
Much thanks to @tlo9, much of this came from his [original PR](https://github.com/wandb/openui/pull/101).

Resolves https://github.com/wandb/openui/issues/73
Resolves https://github.com/wandb/openui/issues/81
Resolves https://github.com/wandb/openui/issues/91

### CODE REVIEW

**Comment by neelesh-sedin** [comment]
Please update docker-compose.yml as well with GROQ environment variable

**Comment by fire17** [comment]
Nice! You guys are awesome!

**Comment by fire17** [comment]
How do we run it with just groq?
can i skip installing olama? and how do we choose which model it uses?
thanks!

**Comment by fire17** [comment]
Screen Shot 2024-05-14 at 19 44 48
I've cloned the latest main, ran docker built
but it seems like its trying to use openai still
and models from groq dont show up in models
Screen Shot 2024-05-14 at 19 47 41

wondering if i can use openui without openai key at all... i only have a groq key
even if it means i cant upload an image and need to go only by text id still like that,
and even better if theres an alternative to the image loading that doesnt require openai

**Comment by kneelesh48** [comment]
Please update docker-compose.yml as well with GROQ_API_KEY environment variable

**Comment by DiazMichael** [comment]
> Screen Shot 2024-05-14 at 19 44 48 I've cloned the latest main, ran docker built but it seems like its trying to use openai still and models from groq dont show up in models Screen Shot 2024-05-14 at 19 47 41
> 
> wondering if i can use openui without openai key at all... i only have a groq key even if it means i cant upload an image and need to go only by text id still like that, and even better if theres an alternative to the image loading that doesnt require openai

Having the same issue of the Groq models not showing of UI. 
To avoid the program to ask for the OPENAI_API_KEY you can just add it as an env variable with any value (Documentation recommends 'xxx')

**Comment by fire17** [comment]
@vanpelt @tlo9 
Can you guys provide more clear instructions on how to run this using groq please?

i've added `GROQ_API_KEY` and `GROQ_BASE_URL` to `docker-compose.yml` as @kneelesh48 suggested, as well as env vars 
ive run `docker-compose build` and 
`docker run -p 7878:7878 -e GROQ_API_KEY -e OPENAI_API_KEY openui-backend`

still getting the same thing (it's trying to get completions from openai)
is this just a matter of choosing the right model? where do you input llama3 or mixtral etc (all groq avail. models)
@DiazMichael How do we add the groq models to the FE ?
is it literally just:
```
cd frontend
pnpm i
npm run deploy
npm run postbuild
```
?

Really hope to get this working
**Thanks a lot and all the best!** 

EDIT: I see that the `main` branch has updates, will try again, but really all this should be seemless, once `-e GROQ_API_KEY` is used

**Comment by vanpelt** [comment]
The main branch should default to groq llama3 70b if it's available.  You can switch models from the settings icon in the upper left corner of the screen.

**Pull request merged**
